package plugin

import (
	"strings"
	"testing"

	"github.com/go-kratos/protoc-gen-typescript-http/internal/codegen"
	"google.golang.org/protobuf/reflect/protodesc"
	"google.golang.org/protobuf/reflect/protoreflect"
	"google.golang.org/protobuf/types/descriptorpb"
	"gotest.tools/v3/assert"
)

// newFileDescriptor is a thin wrapper around protodesc.NewFile that panics on
// error so test authors can focus on the shape of the input.
func newFileDescriptor(t *testing.T, fd *descriptorpb.FileDescriptorProto) protoreflect.FileDescriptor {
	t.Helper()
	f, err := protodesc.NewFile(fd, nil)
	assert.NilError(t, err)
	return f
}

// messageSnapshot builds a single-file descriptor with one message that has
// the supplied fields, then runs messageGenerator and returns the output.
func messageSnapshot(t *testing.T, fields []*descriptorpb.FieldDescriptorProto) string {
	t.Helper()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/test.proto"),
		Package: strPtr("snap"),
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name:  strPtr("TestMessage"),
				Field: fields,
			},
		},
	}
	f := newFileDescriptor(t, fd)
	msg := f.Messages().Get(0)
	var buf codegen.File
	buf.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	buf.P("/* eslint-disable camelcase */")
	buf.P("const encode = (s: string) => encodeURIComponent(s);")
	buf.P()
	gen := messageGenerator{pkg: f.Package(), message: msg}
	gen.Generate(&buf)
	return string(buf.Content())
}

// enumSnapshot builds a single-file descriptor with one enum and runs
// enumGenerator, returning the output.
func enumSnapshot(t *testing.T, values []*descriptorpb.EnumValueDescriptorProto) string {
	t.Helper()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/enum.proto"),
		Package: strPtr("snap"),
		EnumType: []*descriptorpb.EnumDescriptorProto{
			{
				Name:  strPtr("Color"),
				Value: values,
			},
		},
	}
	f := newFileDescriptor(t, fd)
	enum := f.Enums().Get(0)
	var buf codegen.File
	buf.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	buf.P("/* eslint-disable camelcase */")
	buf.P("const encode = (s: string) => encodeURIComponent(s);")
	buf.P()
	gen := enumGenerator{pkg: f.Package(), enum: enum}
	gen.Generate(&buf)
	return string(buf.Content())
}

// packageSnapshot builds a single-file descriptor with one message and one
// enum, then runs packageGenerator, returning the index.ts content.
func packageSnapshot(t *testing.T) string {
	t.Helper()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/pkg.proto"),
		Package: strPtr("snap"),
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strPtr("Item"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("id"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: strPtr("id")},
				},
			},
		},
		EnumType: []*descriptorpb.EnumDescriptorProto{
			{
				Name: strPtr("Status"),
				Value: []*descriptorpb.EnumValueDescriptorProto{
					{Name: strPtr("UNKNOWN"), Number: int32Ptr(0)},
					{Name: strPtr("ACTIVE"), Number: int32Ptr(1)},
				},
			},
		},
	}
	f := newFileDescriptor(t, fd)
	var buf codegen.File
	gen := packageGenerator{pkg: f.Package(), files: []protoreflect.FileDescriptor{f}}
	err := gen.Generate(&buf)
	assert.NilError(t, err)
	return string(buf.Content())
}

func boolPtr(b bool) *bool {
	v := b
	return &v
}

func fieldLabel(l descriptorpb.FieldDescriptorProto_Label) *descriptorpb.FieldDescriptorProto_Label {
	v := l
	return &v
}

// ---------------------------------------------------------------------------
// Message generator snapshots
// ---------------------------------------------------------------------------

func Test_messageGenerator_scalarFields(t *testing.T) {
	t.Parallel()
	got := messageSnapshot(t, []*descriptorpb.FieldDescriptorProto{
		{Name: strPtr("name"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: strPtr("name")},
		{Name: strPtr("age"), Number: int32Ptr(2), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_INT32), JsonName: strPtr("age")},
		{Name: strPtr("active"), Number: int32Ptr(3), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_BOOL), JsonName: strPtr("active")},
	})

	assert.Assert(t, strings.Contains(got, "export type TestMessage = {"), "expected type declaration, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "name?: string;"), "expected string field, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "age?: number;"), "expected number field, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "active?: boolean;"), "expected boolean field, got:\n%s", got)
}

func Test_messageGenerator_optionalField(t *testing.T) {
	t.Parallel()
	got := messageSnapshot(t, []*descriptorpb.FieldDescriptorProto{
		{
			Name:     strPtr("nickname"),
			Number:   int32Ptr(1),
			Type:     fieldType(descriptorpb.FieldDescriptorProto_TYPE_STRING),
			JsonName: strPtr("nickname"),
			Label:    descriptorpb.FieldDescriptorProto_LABEL_OPTIONAL.Enum(),
		},
	})

	// proto3 optional fields should use `?:` syntax.
	assert.Assert(t, strings.Contains(got, "nickname?: string;"), "expected optional field, got:\n%s", got)
}

func Test_messageGenerator_repeatedField(t *testing.T) {
	t.Parallel()
	got := messageSnapshot(t, []*descriptorpb.FieldDescriptorProto{
		{
			Name:     strPtr("tags"),
			Number:   int32Ptr(1),
			Label:    descriptorpb.FieldDescriptorProto_LABEL_REPEATED.Enum(),
			Type:     fieldType(descriptorpb.FieldDescriptorProto_TYPE_STRING),
			JsonName: strPtr("tags"),
		},
	})

	assert.Assert(t, strings.Contains(got, "tags: string[] | undefined;"), "expected array field, got:\n%s", got)
}

func Test_messageGenerator_enumField(t *testing.T) {
	t.Parallel()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/enumfield.proto"),
		Package: strPtr("snap"),
		EnumType: []*descriptorpb.EnumDescriptorProto{
			{
				Name: strPtr("Status"),
				Value: []*descriptorpb.EnumValueDescriptorProto{
					{Name: strPtr("UNKNOWN"), Number: int32Ptr(0)},
					{Name: strPtr("ACTIVE"), Number: int32Ptr(1)},
				},
			},
		},
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strPtr("Item"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("status"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_ENUM), TypeName: strPtr(".snap.Status"), JsonName: strPtr("status")},
				},
			},
		},
	}
	f := newFileDescriptor(t, fd)
	msg := f.Messages().Get(0)
	var buf codegen.File
	buf.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	buf.P("/* eslint-disable camelcase */")
	buf.P("const encode = (s: string) => encodeURIComponent(s);")
	buf.P()
	gen := messageGenerator{pkg: f.Package(), message: msg}
	gen.Generate(&buf)
	got := string(buf.Content())

	assert.Assert(t, strings.Contains(got, "status?: Status;"), "expected enum field reference, got:\n%s", got)
}

func Test_messageGenerator_messageField(t *testing.T) {
	t.Parallel()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/nested.proto"),
		Package: strPtr("snap"),
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strPtr("Inner"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("value"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: strPtr("value")},
				},
			},
			{
				Name: strPtr("Outer"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("inner"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: strPtr(".snap.Inner"), JsonName: strPtr("inner")},
				},
			},
		},
	}
	f := newFileDescriptor(t, fd)
	msg := f.Messages().Get(1) // Outer
	var buf codegen.File
	buf.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	buf.P("/* eslint-disable camelcase */")
	buf.P("const encode = (s: string) => encodeURIComponent(s);")
	buf.P()
	gen := messageGenerator{pkg: f.Package(), message: msg}
	gen.Generate(&buf)
	got := string(buf.Content())

	assert.Assert(t, strings.Contains(got, "inner?: Inner;"), "expected message field reference, got:\n%s", got)
}

// ---------------------------------------------------------------------------
// Oneof generator snapshots
// ---------------------------------------------------------------------------

func Test_messageGenerator_oneofScalarFields(t *testing.T) {
	t.Parallel()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/oneof.proto"),
		Package: strPtr("snap"),
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strPtr("Shape"),
				OneofDecl: []*descriptorpb.OneofDescriptorProto{
					{Name: strPtr("kind")},
				},
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("radius"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_FLOAT), JsonName: strPtr("radius"), OneofIndex: int32Ptr(0)},
					{Name: strPtr("side"), Number: int32Ptr(2), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_FLOAT), JsonName: strPtr("side"), OneofIndex: int32Ptr(0)},
				},
			},
		},
	}
	f := newFileDescriptor(t, fd)
	msg := f.Messages().Get(0)
	var buf codegen.File
	buf.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	buf.P("/* eslint-disable camelcase */")
	buf.P("const encode = (s: string) => encodeURIComponent(s);")
	buf.P()
	gen := messageGenerator{pkg: f.Package(), message: msg}
	gen.Generate(&buf)
	got := string(buf.Content())

	// Should generate a discriminated union, not a flat struct.
	assert.Assert(t, strings.Contains(got, "export type Shape ="), "expected union type, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "$case: \"radius\""), "expected radius $case, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "radius: number"), "expected radius field, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "$case: \"side\""), "expected side $case, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "side: number"), "expected side field, got:\n%s", got)
	// Should NOT generate a flat struct.
	assert.Assert(t, !strings.Contains(got, "export type Shape = {"), "expected union instead of struct, got:\n%s", got)
}

func Test_messageGenerator_oneofMessageField(t *testing.T) {
	t.Parallel()
	fd := &descriptorpb.FileDescriptorProto{
		Name:    strPtr("snap/oneof_nested.proto"),
		Package: strPtr("snap"),
		MessageType: []*descriptorpb.DescriptorProto{
			{
				Name: strPtr("Inner"),
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("value"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: strPtr("value")},
				},
			},
			{
				Name: strPtr("Outer"),
				OneofDecl: []*descriptorpb.OneofDescriptorProto{
					{Name: strPtr("payload")},
				},
				Field: []*descriptorpb.FieldDescriptorProto{
					{Name: strPtr("text"), Number: int32Ptr(1), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_STRING), JsonName: strPtr("text"), OneofIndex: int32Ptr(0)},
					{Name: strPtr("inner"), Number: int32Ptr(2), Type: fieldType(descriptorpb.FieldDescriptorProto_TYPE_MESSAGE), TypeName: strPtr(".snap.Inner"), JsonName: strPtr("inner"), OneofIndex: int32Ptr(0)},
				},
			},
		},
	}
	f := newFileDescriptor(t, fd)
	msg := f.Messages().Get(1) // Outer
	var buf codegen.File
	buf.P("// Code generated by protoc-gen-typescript-http. DO NOT EDIT.")
	buf.P("/* eslint-disable camelcase */")
	buf.P("const encode = (s: string) => encodeURIComponent(s);")
	buf.P()
	gen := messageGenerator{pkg: f.Package(), message: msg}
	gen.Generate(&buf)
	got := string(buf.Content())

	assert.Assert(t, strings.Contains(got, "export type Outer ="), "expected union type, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "$case: \"text\""), "expected text $case, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "text: string"), "expected text field, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "$case: \"inner\""), "expected inner $case, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "inner: Inner"), "expected inner message reference, got:\n%s", got)
}

// ---------------------------------------------------------------------------
// Enum generator snapshots
// ---------------------------------------------------------------------------

func Test_enumGenerator_multiValue(t *testing.T) {
	t.Parallel()
	got := enumSnapshot(t, []*descriptorpb.EnumValueDescriptorProto{
		{Name: strPtr("RED"), Number: int32Ptr(0)},
		{Name: strPtr("GREEN"), Number: int32Ptr(1)},
		{Name: strPtr("BLUE"), Number: int32Ptr(2)},
	})

	assert.Assert(t, strings.Contains(got, "export type Color ="), "expected type alias, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "\"RED\""), "expected RED, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "\"GREEN\""), "expected GREEN, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "\"BLUE\""), "expected BLUE, got:\n%s", got)
}

func Test_enumGenerator_singleValue(t *testing.T) {
	t.Parallel()
	got := enumSnapshot(t, []*descriptorpb.EnumValueDescriptorProto{
		{Name: strPtr("UNKNOWN"), Number: int32Ptr(0)},
	})

	assert.Assert(t, strings.Contains(got, "export type Color ="), "expected single-value enum, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "\"UNKNOWN\""), "expected UNKNOWN, got:\n%s", got)
}

// ---------------------------------------------------------------------------
// Package generator snapshot
// ---------------------------------------------------------------------------

func Test_packageGenerator_indexStructure(t *testing.T) {
	t.Parallel()
	got := packageSnapshot(t)

	// Header is emitted.
	assert.Assert(t, strings.Contains(got, "// Code generated by protoc-gen-typescript-http. DO NOT EDIT."), "expected header, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "const encode = (s: string) => encodeURIComponent(s);"), "expected encode helper, got:\n%s", got)
	// Enum and message are both generated (no package prefix since file package == gen package).
	assert.Assert(t, strings.Contains(got, "export type Status ="), "expected enum type, got:\n%s", got)
	assert.Assert(t, strings.Contains(got, "export type Item ="), "expected message type, got:\n%s", got)
	_ = got
}
