name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Setup buf
        uses: bufbuild/buf-setup-action@v1
        with:
          version: '1.69.0'

      - name: Install mage
        run: go install github.com/magefile/mage@v1.17.2

      - name: Run unit tests
        run: mage test

      - name: Run integration tests
        run: mage integration
